spring:
  application:
    name: rentitup
  mail:
    host: smtp.gmail.com
    port: 587
    username: mumbamarkian@gmail.com
    password: fcadyqetkutmufmp
    properties:
      mail:
        smtp:
          auth: true
          starttls: enable
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 15780816329-lvb8bli22grtdhs37s6jrgdehsa5fbdl.apps.googleusercontent.com
            client-secret: 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
  datasource:
    url: jdbc:postgresql://localhost:5435/rentitups
    username: administrator
    password: qwerty1234
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000

aws:
  s3:
    access-key: AKIAVIOAD3DSP3BOOQ3S
    secret-key: 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


bucket-name: hotel-gallery

frontend:
  url: http://localhost:3000


