spring:
  application:
    name: rentitup


  datasource:
    url: jdbc:postgresql://localhost:5435/rentitups
    username: administrator
    password: qwerty1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000

aws:
  s3:
    access-key: AKIAVIOAD3DSP3BOOQ3S
    secret-key: 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

bucket-name: hotel-gallery


